homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage import users, index, authentication
from homepage import addLog, clients, search

urlpatterns = [
    path('index/', index.index, name='index'),
    path('', authentication.login, name='login'),
    path('login/', authentication.login, name='login'),
    path('logout/', authentication.logout, name='logout'),
    path('add_log/<int:id>', addLog.add_log, name='add_log'),
    path('add_client/', clients.add_client, name='add_client'),
    path('client_profile/<int:id>', clients.client_profile, name='client_profile'),
    path('edit_client/<int:id>', clients.edit_client, name='edit_client'),
    path('delete_client/<int:id>', clients.delete_client, name='delete_client'),
    path('inactive_clients/', clients.inactive_clients, name='inactive_clients'),
    path('search/', search.search, name='search'),
    path('search_interns/', search.search_interns, name='search_interns'),
    path('add_bookmark/<int:id>', users.add_bookmark, name='add_bookmark'),
    path('admin_portal/', users.admin_portal, name='admin_portal'),
    path('intern_portal/', users.intern_portal, name='intern_portal'),
    path('edit_profile/', users.edit_profile, name='edit_profile'),
    path('admin_edit_profile/<int:id>', users.admin_edit_profile, name='admin_edit_profile'),
    path('add_intern/', users.add_intern, name='add_intern'),
    path('deactivate_intern/<int:id>', users.deactivate_intern, name='deactivate_intern'),
]

seedsite/seedsite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

seedsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
]

homepage/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime, date
from django.conf import settings

class Intern(AbstractUser):
    # username
    # password
    first_name = models.TextField(blank=False, null=True)
    last_name = models.TextField(blank=False, null=True)
    email = models.EmailField()
    semester = models.TextField(blank=False, null=True)
    year = models.TextField(blank=False, null=True)
    location = models.TextField(blank=False, null=True)
    is_previously_logged_in = models.BooleanField(default=False)

class AssignedClient(models.Model):
    intern = models.ForeignKey('Intern', on_delete=models.CASCADE)
    client = models.ForeignKey('Client', on_delete=models.CASCADE)

class Client(models.Model):
    image = models.ImageField(blank=True)
    first_name = models.TextField(blank=True, null=True)
    last_name = models.TextField(blank=True, null=True)
    gender = models.TextField(blank=True, null=True)
    email = models.EmailField()
    phone_number = models.CharField(blank=True, null=True, max_length=11)
    language = models.TextField(blank=True, null=True)
    literacy = models.TextField(blank=True, null=True)
    semester = models.TextField(blank=True, null=True)
    year = models.TextField(blank=True, null=True)
    location = models.TextField(blank=True, null=True)
    organization = models.TextField(blank=True, null=True)
    lat = models.DecimalField(max_digits=20, decimal_places=15, blank=True, null=True)
    lon = models.DecimalField(max_digits=20, decimal_places=15, blank=True, null=True)
    business_name = models.TextField(blank=True, null=True)
    business_type = models.TextField(blank=True, null=True)
    transportation_method = models.TextField(blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    active = models.BooleanField(blank=False, default=True)

class Log(models.Model):
    date_created = models.DateField(auto_now_add=True)
    date_visited = models.DateField(blank=True, null=True)
    visit_description = models.TextField(blank=True, null=True)
    next_steps = models.TextField(blank=True, null=True)
    time_of_visit = models.TextField(blank=True, null=True)
    intern = models.ForeignKey('Intern', on_delete=models.CASCADE)
    client = models.ForeignKey('Client', on_delete=models.CASCADE)

homepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'CR_Logo_favicon.png' %}">

    <title>{% block title %}Home{% endblock title %} | SEED Philippines</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <!-- Custom Css -->
    <link rel="stylesheet" href="https://use.typekit.net/oom3tjf.css">
    <link href="{% static 'main.css' %}" rel="stylesheet" type="text/css">

    <!-- animation package -->
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <script src="https://use.fontawesome.com/e32a5ff2e3.js"></script>

    <!-- bootstrap js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    {% block resources %}
    {% endblock resources %}
</head>

<body>
    {% block alerts %}
    {% endblock alerts %}
    <!-- top navigation -->
    <nav id="top" class="navbar navbar-light">
      <a class="navbar-brand" href="/index">
        <img src="{% static "CR_Logo_New_Black.svg" %}" width="55" height="auto" alt="The CR">
      </a>
      <!-- <a href="/logout"> <img src="{% static "sign-out.svg" %}" alt="Sign Out" width="30" height="auto"> </a> -->
      <a href="/logout"><i class="fa fa-sign-out-alt fa-2x" style="color:black;"></i> </a>
    </nav>

    <div class="container mt-3" style="padding-bottom:70px;">
        <div class="row">
            <div class="col-12">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>

    <!-- bottom navigation -->
    <ul id="bottom-navbar" class="nav justify-content-around fixed-bottom">
        {% if  perms.homepage.intern_portal %}
            <li class="nav-item">
                <a class="nav-link" href="/index"> <i class="fa fa-home fa-2x bottom-nav-link id-intern-portal"></i> </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/edit_profile"> <i class="fa fa-user-astronaut fa-2x bottom-nav-link id-profile"></i> </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/intern_portal/#top"> <i class="fa fa-search fa-2x bottom-nav-link id-search"></i> </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/add_client"> <i class="fa fa-user-plus fa-2x bottom-nav-link id-add"></i> </a>
            </li>
        {% elif perms.homepage.admin_portal %}
            <li class="nav-item">
                <a class="nav-link" href="/index"> <i class="fa fa-home fa-2x bottom-nav-link id-admin-portal"></i> </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/intern_portal"> <i class="fa fa-address-card fa-2x bottom-nav-link id-intern-portal"></i> </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/edit_profile"> <i class="fa fa-user-astronaut fa-2x bottom-nav-link id-profile"></i> </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/add_intern"> <i class="fa fa-user-plus fa-2x bottom-nav-link id-add"></i> </a>
            </li>
        {% endif %}
    </ul>
        <script type="text/javascript" src="{% static "main.js" %}">     </script>
</body>

homepage/templates/homepage/add_client.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Add Client
{% endblock title %}

{% block resources %}

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
crossorigin=""></script>


{% endblock resources %}

{% block content %}
<div class="where-am-i">id-add</div>
<h1 class="text-center">Add Client</h1>
<!-- <hr> -->
<form class="" action="/add_client/" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <h3 class="text-left">Personal Information:</h3>
  <hr>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.image.errors}}
      <label for="{{form.image.id_for_label}}">Client Image</label>
      <div class="input-group">
        {{form.image}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.first_name.errors}}
      <label for="{{form.first_name.id_for_label}}">First Name</label>
      <div class="input-group">
        {{form.first_name}}
      </div>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.last_name.errors}}
      <label for="{{form.last_name.id_for_label}}">Last Name</label>
      <div class="input-group">
        {{form.last_name}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.gender.errors}}
      <label for="{{form.gender.id_for_label}}">Gender</label>
      <div class="input-group">
        {{form.gender}}
      </div>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.email.errors}}
      <label for="{{form.email.id_for_label}}">Email</label>
      <div class="input-group">
        {{form.email}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.phone_number.errors}}
      <label for="{{form.phone_number.id_for_label}}">Phone Number</label>
      <div class="input-group">
        {{form.phone_number}}
      </div>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.language.errors}}
      <label for="{{form.language.id_for_label}}">Language</label>
      <div class="input-group">
        {{form.language}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.literacy.errors}}
      <label for="{{form.literacy.id_for_label}}">Literacy</label>
      <div class="input-group">
        {{form.literacy}}
      </div>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.organization.errors}}
      <label for="{{form.organization.id_for_label}}">Organization</label>
      <div class="input-group">
        {{form.organization}}
      </div>
      <br>
    </div>
  </div>
  <h3 class="text-left">Bio:</h3>
  <hr>
  <div class="row">
    <div class="col-md-12 input-label">
      {{form.bio.errors}}
      <!-- <label for="{{form.bio.id_for_label}}">Bio</label> -->
      <div class="input-group">
        {{form.bio}}
      </div>
      <br>
    </div>
  </div>
  <h3 class="text-left">Business Information:</h3>
  <hr>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.business_name.errors}}
      <label for="{{form.business_name.id_for_label}}">Business Name</label>
      <div class="input-group">
        {{form.business_name}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.business_type.errors}}
      <label for="{{form.business_type.id_for_label}}">Business Type</label>
      <div class="input-group">
        {{form.business_type}}
      </div>
      <br>
    </div>
  </div>
  <h3 class="text-left">Getting There:</h3>
  <hr>
  <div class="row">
    <div class="col-md-12 mb-4">
      <label for="{{form.location.id_for_label}}">Place Pin</label>
      <div id='mapid' class="container"></div>
      <script>
        var mymap = L.map('mapid').setView([{{map_lat}}, {{map_lon}}], 13);
        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
          attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
          maxZoom: 18,
          id: 'mapbox.streets',
          accessToken: 'pk.eyJ1IjoiYmVudG9uc21pdGgiLCJhIjoiY2pqZjl0ZjBvMGN1YjN2bXN1Y2ZvcDY0ayJ9.V8OFcjbPM7l1gaMsWQxudA'
        }).addTo(mymap);
        var myIcon = L.icon({
          iconUrl: "{% static "map_pin.png" %}",
          iconSize: [38, 70],
          iconAnchor: [19, 70],
        });
        var marker = L.marker([{{map_lat}}, {{map_lon}}], {icon: myIcon, draggable: 'True', title:'Drag to set location', autoPan: 'True'}).addTo(mymap);
        marker.on('moveend', setlatlon);
        function setlatlon(){

          var newlocation = marker.getLatLng();
          console.log(newlocation);
          $('#id_lat').attr('value', newlocation.lat);
          $('#id_lon').attr('value', newlocation.lng);
        }
      </script>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.lat.errors}}
      <label for="{{form.lat.id_for_label}}">Latitude <span style="font-size:1rem;">(auto-populated from map)</span></label>
      <div id="enterlat" class="input-group">
        {{form.lat}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.lon.errors}}
      <label for="{{form.lon.id_for_label}}">Longitude <span style="font-size:1rem;">(auto-populated from map)</span> </label>
      <div id="enterlon" class="input-group">
        {{form.lon}}
      </div>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.transportation_method.errors}}
      <label for="{{form.transportation_method.id_for_label}}">Transportation Method</label>
      <div class="input-group">
        {{form.transportation_method}}
      </div>
      <br>
    </div>
  </div>
  <div class="container d-flex justify-content-center">
    <input class="btn btn-success" value="Save" type="submit"></input>
  </div>
</form>

{% endblock content %}

homepage/templates/homepage/add_log.html
{% extends "base.html" %}
{% load static %}

{% block resources %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
$(function(){
    $("#id_date_visited").datepicker();
});
</script>
{% endblock resources %}

{% block content %}
<h1 class="text-center">Add Log</h1>
<hr>
<div class="container mb-5">
    <form class="" action="/add_log/{{current_client.id}}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6 input-label">
                {{form.visit_description.errors}}
                <label for="{{form.visit_description.id_for_label}}">Visit Description</label>
                <div class="input-group">
                    {{form.visit_description}}
                </div>
                <br>
            </div>
            <div class="col-md-6 input-label">
                {{form.next_steps.errors}}
                <label for="{{form.next_steps.id_for_label}}">Next Steps</label>
                <div class="input-group">
                    {{form.next_steps}}
                </div>
                <br>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col-6 input-label d-flex align-items-center">
                {{form.date_visited.errors}}
                <label for="{{form.date_visited.id_for_label}}">Date Visited</label>
            </div>
            <div class="col-6 input-label d-flex align-items-center">
                <div class="input-group" id="datepicker">
                    {{form.date_visited}}
                </div>
                <br>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col-6 input-label d-flex align-items-center">
                {{form.time_of_visit.errors}}
                <label for="{{form.time_of_visit.id_for_label}}">Time Of Visit</label>
            </div>
            <div class="col-6 input-label d-flex align-items-center">
                <div class="input-group">
                    {{form.time_of_visit}}
                </div>
                <br>
            </div>
        </div>
        <br>
        <div class="container d-flex justify-content-center">
            <input class="btn btn-success" value="Save" type="submit"></input>
        </div>

    </form>
</div>
{% endblock content %}

homepage/templates/homepage/admin_portal.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Admin Portal
{% endblock title %}

{% block resources %}
<link rel="stylesheet" href="{% static "homepage/admin_portal.css" %}">
{% endblock resources %}

{% block content %}
<div class="where-am-i">id-admin-portal</div>
<div class="col-12 col-xs-12 offset-xs-0 col-sm-8 offset-sm-2 col-md-12 offset-md-0 col-lg-12 offset-lg-0 col-mb-4">
<form action="/search_interns/">
    <div class="input-group">
        <input  id="search_box" type="search" class="form-control mr-sm-2" name="intern_name"  placeholder="Search Intern" >
    </div>
</form>
</div>

<div class="container mb-5">
  <div class="row">
    {% for intern in interns %}
    <div class="card col-12 col-xs-12 offset-xs-0 col-sm-8 offset-sm-2 col-md-6 offset-md-0 col-lg-4 offset-lg-0 mb-4 p-2">
        <div class="card-body pl-0 pr-0">
            <div class="container-fluid">
                <div class="row d-flex align-items-center justify-content-center">
                    <div class="col-12">
                        <a href="/admin_edit_profile/{{intern.id}}">
                            <h4 class="text-center"> <strong>{{ intern.first_name }} {{ intern.last_name}}</strong> | <span style="font-size:1rem;">{{ intern.semester }} {{ intern.year }}</span></h4>
                        </a>
                        <a href="mailto:{{intern.email}}">
                            <h6 class="text-center">{{ intern.email }}</h6>
                        </a>
                        <br>
                        <h5 class="text-center">Bookmarked Clients</h5>
                        <hr class="mt-1 mb-1">
                        {% for pair in assigned_clients %}
                            {% if pair.intern.id == intern.id %}
                                    <h5 class="text-center p-2" style="font-weight:200;"><a href="/client_profile/{{pair.client.id}}">{{pair.client.first_name}} {{pair.client.last_name}}</a></h5>
                            {% endif %}
                        {% endfor %}
                        <h5></h5>
                    </div>

                </div>
            </div>
        </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock content %}

homepage/templates/homepage/edit_client.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Edit Client
{% endblock title %}

{% block resources %}

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
crossorigin=""></script>


{% endblock resources %}

{% block content %}
<h1 class="text-center">Edit Client</h1>
<!-- <hr> -->
<form class="" action="/edit_client/{{current_client.id}}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <h3 class="text-left">Personal Information:</h3>
  <hr>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.image.errors}}
      <label for="{{form.image.id_for_label}}">Client Image</label>
      <div class="input-group">
        {{form.image}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.first_name.errors}}
      <label for="{{form.first_name.id_for_label}}">First Name</label>
      <div class="input-group">
        {{form.first_name}}
      </div>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.last_name.errors}}
      <label for="{{form.last_name.id_for_label}}">Last Name</label>
      <div class="input-group">
        {{form.last_name}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.gender.errors}}
      <label for="{{form.gender.id_for_label}}">Gender</label>
      <div class="input-group">
        {{form.gender}}
      </div>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.email.errors}}
      <label for="{{form.email.id_for_label}}">Email</label>
      <div class="input-group">
        {{form.email}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.phone_number.errors}}
      <label for="{{form.phone_number.id_for_label}}">Phone Number</label>
      <div class="input-group">
        {{form.phone_number}}
      </div>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.language.errors}}
      <label for="{{form.language.id_for_label}}">Language</label>
      <div class="input-group">
        {{form.language}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.literacy.errors}}
      <label for="{{form.literacy.id_for_label}}">Literacy</label>
      <div class="input-group">
        {{form.literacy}}
      </div>
      <br>
    </div>
  </div>
  <h3 class="text-left">Bio:</h3>
  <hr>
  <div class="row">
    <div class="col-md-12 input-label">
      {{form.bio.errors}}
      <!-- <label for="{{form.bio.id_for_label}}">Bio</label> -->
      <div class="input-group">
        {{form.bio}}
      </div>
      <br>
    </div>
  </div>
  <h3 class="text-left">Business Information:</h3>
  <hr>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.business_name.errors}}
      <label for="{{form.business_name.id_for_label}}">Business Name</label>
      <div class="input-group">
        {{form.business_name}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.business_type.errors}}
      <label for="{{form.business_type.id_for_label}}">Business Type</label>
      <div class="input-group">
        {{form.business_type}}
      </div>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.location.errors}}
      <label for="{{form.location.id_for_label}}">Location</label>
      <div class="input-group">
        {{form.location}}
      </div>
      <br>
    </div>
  </div>
  <h3 class="text-left">Getting There:</h3>
  <hr>
  <div class="row">
    <div class="col-md-12 mb-4">
      <label for="{{form.country.id_for_label}}">Place Pin</label>
      <div id='mapid' class="container"></div>
      <script>
        var mymap = L.map('mapid').setView([{{current_client.lat}}, {{current_client.lon}}], 13);
        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
          attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
          maxZoom: 18,
          id: 'mapbox.streets',
          accessToken: 'pk.eyJ1IjoiYmVudG9uc21pdGgiLCJhIjoiY2pqZjl0ZjBvMGN1YjN2bXN1Y2ZvcDY0ayJ9.V8OFcjbPM7l1gaMsWQxudA'
        }).addTo(mymap);
        var myIcon = L.icon({
          iconUrl: "{% static "map_pin.png" %}",
          iconSize: [38, 70],
          iconAnchor: [19, 70],
        });
        var marker = L.marker([{{current_client.lat}}, {{current_client.lon}}], {icon: myIcon, draggable: 'True', title:'Drag to set location', autoPan: 'True'}).addTo(mymap);
        marker.on('moveend', setlatlon);
        function setlatlon(){

          var newlocation = marker.getLatLng();
          console.log(newlocation);
          $('#id_lat').attr('value', newlocation.lat);
          $('#id_lon').attr('value', newlocation.lng);
        }
      </script>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.lat.errors}}
      <label for="{{form.lat.id_for_label}}">Latitude <span style="font-size:1rem;">(auto-populated from map)</span></label>
      <div id="enterlat" class="input-group">
        {{form.lat}}
      </div>
      <br>
    </div>
    <div class="col-md-6 input-label">
      {{form.lon.errors}}
      <label for="{{form.lon.id_for_label}}">Longitude <span style="font-size:1rem;">(auto-populated from map)</span> </label>
      <div id="enterlon" class="input-group">
        {{form.lon}}
      </div>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 input-label">
      {{form.transportation_method.errors}}
      <label for="{{form.transportation_method.id_for_label}}">Transportation Method</label>
      <div class="input-group">
        {{form.transportation_method}}
      </div>
      <br>
    </div>
  </div>
  <div class="container d-flex justify-content-center">
    <input class="btn btn-success" value="Save" type="submit"></input>
  </div>
</form>

{% if current_client.active == True %}
<!-- Button trigger modal -->
<a class="btn deactivate d-flex justify-content-center" data-toggle="modal" data-target="#Modal">Deactivate</a>
{% elif current_client.active == False %}
<a href="/delete_client/{{current_client.id}}" class="btn reactivate d-flex justify-content-center">Reactivate</a>
{% endif %}


<!-- Modal -->
<div class="modal fade mt-5" id="Modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLabel">Hold up! Wait a minute.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to deactivate this client? The client will only be viewable from the search bar.
      </div>
      <div class="modal-footer">
        <a class="btn btn-danger modal-danger ml-auto" href="/delete_client/{{current_client.id}}">Deactivate</a>
        <a class="btn btn-primary mr-auto" data-dismiss="modal" style="color:white;">Close</a>
        <img id="waiting-gif" src="{% static "waiting.gif" %}" alt="">
      </div>
    </div>
  </div>

  {% endblock content %}